# Generated by Django 4.2.6 on 2024-05-09 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='***', max_length=120, verbose_name='نام کروه')),
                ('Family', models.CharField(default='***', max_length=120, verbose_name='نام کروه')),
                ('Code', models.IntegerField(default=0, verbose_name='کد کروه')),
                ('Status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('Desc', models.CharField(blank=True, default='***', max_length=500, null=True, verbose_name='توضیحات')),
                ('Create_Date', models.DateTimeField(auto_now=True, null=True)),
                ('Update_Date', models.DateTimeField(auto_now=True, null=True)),
                ('Create_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده')),
                ('Create_UName', models.CharField(blank=True, default='--', max_length=120, null=True, verbose_name='نام کاربر ایجاد کننده')),
                ('Update_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ویرایش کننده')),
            ],
            options={
                'db_table': 'Customers',
                'ordering': ['id'],
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin')),
            },
        ),
        migrations.CreateModel(
            name='CustomersGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='***', max_length=120, verbose_name='نام کروه')),
                ('Code', models.IntegerField(default=0, verbose_name='کد کروه')),
                ('Status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('Desc', models.CharField(blank=True, default='***', max_length=500, null=True, verbose_name='توضیحات')),
                ('Create_Date', models.DateTimeField(auto_now=True, null=True)),
                ('Update_Date', models.DateTimeField(auto_now=True, null=True)),
                ('Create_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده')),
                ('Create_UName', models.CharField(blank=True, default='--', max_length=120, null=True, verbose_name='نام کاربر ایجاد کننده')),
                ('Update_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ویرایش کننده')),
            ],
            options={
                'db_table': 'CustomersGroup',
                'ordering': ['id'],
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin')),
            },
        ),
        migrations.CreateModel(
            name='GoodsAndServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='***', max_length=120, verbose_name='نام کروه/کالا')),
                ('Code', models.IntegerField(default=0, verbose_name='کد کروه/کالا')),
                ('isGroup', models.BooleanField(default=False, verbose_name='تعیین گروه')),
                ('Status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('Desc', models.CharField(blank=True, default='***', max_length=500, null=True, verbose_name='توضیحات')),
                ('Create_Date', models.DateTimeField(auto_now=True, null=True)),
                ('Update_Date', models.DateTimeField(auto_now=True, null=True)),
                ('Create_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده')),
                ('Create_UName', models.CharField(blank=True, default='--', max_length=120, null=True, verbose_name='نام کاربر ایجاد کننده')),
                ('Update_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ویرایش کننده')),
            ],
            options={
                'db_table': 'GoodsAndServices',
                'ordering': ['id'],
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin')),
            },
        ),
        migrations.CreateModel(
            name='ReceiptAndRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='***', max_length=120, verbose_name='نام کروه/کالا')),
                ('Code', models.IntegerField(default=0, verbose_name='کد کروه/کالا')),
                ('isGroup', models.BooleanField(default=False, verbose_name='تعیین گروه')),
                ('Status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('Desc', models.CharField(blank=True, default='***', max_length=500, null=True, verbose_name='توضیحات')),
                ('Create_Date', models.DateTimeField(auto_now=True, null=True)),
                ('Update_Date', models.DateTimeField(auto_now=True, null=True)),
                ('Create_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده')),
                ('Create_UName', models.CharField(blank=True, default='--', max_length=120, null=True, verbose_name='نام کاربر ایجاد کننده')),
                ('Update_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ویرایش کننده')),
            ],
            options={
                'db_table': 'ReceiptAndRemittance',
                'ordering': ['id'],
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin')),
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='***', max_length=120, verbose_name='نام انبار')),
                ('Code', models.IntegerField(default=0, verbose_name='کد انبار')),
                ('Status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('Desc', models.CharField(blank=True, default='***', max_length=500, null=True, verbose_name='توضیحات')),
                ('Create_Date', models.DateTimeField(auto_now=True, null=True)),
                ('Update_Date', models.DateTimeField(auto_now=True, null=True)),
                ('Create_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده')),
                ('Create_UName', models.CharField(blank=True, default='--', max_length=120, null=True, verbose_name='نام کاربر ایجاد کننده')),
                ('Update_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ویرایش کننده')),
            ],
            options={
                'db_table': 'Store',
                'ordering': ['id'],
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin')),
            },
        ),
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField(default=0, verbose_name='کد')),
                ('Count', models.IntegerField(default=0, verbose_name='مبلغ')),
                ('Type', models.IntegerField(blank=True, choices=[(0, 'رسید'), (1, 'حواله')], default=0, null=True, verbose_name='نوع فرم')),
                ('Desc', models.CharField(blank=True, default='***', max_length=500, null=True, verbose_name='توضیحات')),
                ('Create_Date', models.DateTimeField(auto_now=True, null=True)),
                ('Update_Date', models.DateTimeField(auto_now=True, null=True)),
                ('Create_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده')),
                ('Create_UName', models.CharField(blank=True, default='--', max_length=120, null=True, verbose_name='نام کاربر ایجاد کننده')),
                ('Update_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ویرایش کننده')),
                ('Custom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Customer', to='StoreMenuApp.customers')),
                ('GoAndSer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='GoASe', to='StoreMenuApp.goodsandservices')),
            ],
            options={
                'db_table': 'Recept',
                'ordering': ['id'],
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin')),
            },
        ),
        migrations.AddField(
            model_name='customers',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CGroup', to='StoreMenuApp.customersgroup'),
        ),
    ]
