# Generated by Django 4.2.6 on 2024-05-12 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreMenuApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='Code',
        ),
    ]
