# Generated by Django 4.2.6 on 2024-05-15 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreMenuApp', '0002_remove_store_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceiptAndRemittance',
        ),
    ]
