# Generated by Django 4.2.6 on 2024-05-15 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreMenuApp', '0003_delete_receiptandremittance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='Code',
        ),
        migrations.RemoveField(
            model_name='customersgroup',
            name='Code',
        ),
        migrations.RemoveField(
            model_name='goodsandservices',
            name='Code',
        ),
        migrations.RemoveField(
            model_name='recept',
            name='Code',
        ),
    ]
