# Generated by Django 4.2.6 on 2024-05-15 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreMenuApp', '0004_remove_customers_code_remove_customersgroup_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsandservices',
            name='isGroup',
        ),
    ]
