# Generated by Django 4.2.6 on 2024-05-18 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoreMenuApp', '0005_remove_goodsandservices_isgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='Sto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Store', to='StoreMenuApp.store'),
            preserve_default=False,
        ),
    ]
